# Generated by Django 4.1.4 on 2023-01-14 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mycourse',
            field=models.ManyToManyField(to='core.course'),
        ),
    ]
