# Generated by Django 4.1.4 on 2023-01-14 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_mycourse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mycourse',
            field=models.ManyToManyField(blank=True, to='core.course'),
        ),
    ]
